[package]
name = "cyrus-lang"
version = "0.0.1"
edition = "2024"
resolver = "2"

[workspace]
members = ["ast", "codegen_llvm", "lexer", "parser", "utils"]

[[bin]]
name = "cyrus"
path = "./cli.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colorized = "1.0.0"
lexer = { path = "./lexer", version = "*" }
ast = { path = "./ast", version = "*" }
parser = { path = "./parser", version = "*" }
utils = { path = "./utils", version = "*" }
codegen_llvm = { path = "./codegen_llvm", version = "*" }
toml = "0.8.20"
