[workspace]
members = [
    "crates/codegen",
    "crates/lexer",
    "crates/parser",
    "crates/ast",
    "crates/utils",
    "crates/layout",
    "crates/diagcentral",
    "crates/typed_ast",
    "crates/cli",
    "crates/static_analyzer", "crates/resolver",
]
default-members = ["crates/cli"]

resolver = "3"

[profile.dev]
codegen-units = 1024
