[package]
name = "cyrus-lang"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = ["ast", "lexer", "parser"]

[[bin]]
name = "cyrus"
path = "./cli.rs"

[dependencies]
llvm-sys = "181.2.0"
clap = { version = "4.5.23", features = ["derive"] }
parser = { path = "./parser", version = "*" }
cyrusc = { path = "./cyrusc", version = "*" }
ast = { path = "./ast", version = "*" }

