[package]
name = "cyrus-lang"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = ["ast", "cli", "compiler", "lexer", "parser"]

[[bin]]
name = "cyrus"
path = "./cli/cli.rs"

[dependencies]
parser = { path = "./parser", version = "*" }
