[package]
name = "cyrus-lang"
version = "0.0.1"
edition = "2024"
resolver = "2"
build = "./build.rs"

[workspace]
members = [
    "crates/codegen_llvm",
    "crates/lexer",
    "crates/parser",
    "crates/ast",
    "crates/utils",
    "crates/cli",
    "crates/layout",
]

[[bin]]
name = "cyrus"
path = "./crates/cli/src/main.rs"

[dependencies]
codegen_llvm = { path = "./crates/codegen_llvm", version = "*" }
layout = { path = "./crates/layout", version = "*" }
parser = { path = "./crates/parser", version = "*" }
clap = { version = "4.5.34", features = ["derive"] }
lexer = { path = "./crates/lexer", version = "*" }
utils = { path = "./crates/utils", version = "*" }
ast = { path = "./crates/ast", version = "*" }
colorized = "1.0.0"
toml = "0.8.20"