[package]
name = "diag"
version = "0.1.0"
edition = "2024"

[dependencies]
ast = { path = "../ast", version = "*" }
utils = { path = "../utils", version = "*" }
colorized = "1.0.0"
console = "0.15.11"