[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
gccjit_sys = "0.5.0"
ast = { path = "../ast", version = "*" }
utils = { path = "../utils", version = "*" }

[build-dependencies]
cc = "1.2.7"