name: Cyrus Linux - Daily Build

on:
  schedule:
    - cron: "0 0 * * *" # every 12 hours if changed to */12
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-24.04

    outputs:
      datetime: ${{ steps.meta.outputs.datetime }}
      artifact: ${{ steps.meta.outputs.artifact }}
      zipfile: ${{ steps.meta.outputs.zipfile }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt install -y software-properties-common llvm-18 llvm-18-dev clang-18 \
            zlib1g zlib1g-dev libpolly-18-dev upx libasan8 zip

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        env:
          LLVM_CONFIG: /usr/bin/llvm-config-18
          CC: clang
          CXX: clang++
        run: |
          set -euo pipefail
          chmod +x ./scripts/release.sh
          ./scripts/release.sh

      - name: Prepare release directory
        run: |
          set -euo pipefail

          mkdir -p cyrus

          test -f ./target/release/cyrus
          test -d ./stdlib

          cp ./target/release/cyrus ./cyrus/
          cp ./scripts/install.sh ./cyrus/
          cp -r ./stdlib ./cyrus/

      - name: Generate build metadata
        id: meta
        run: |
          set -euo pipefail

          DATETIME=$(date +'%Y%m%d-%H%M%S')

          ARTIFACT="cyrus-linux-$DATETIME"
          ZIPFILE="$ARTIFACT.zip"

          echo "datetime=$DATETIME" >> $GITHUB_OUTPUT
          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
          echo "zipfile=$ZIPFILE" >> $GITHUB_OUTPUT

      - name: Create zip archive
        run: |
          set -euo pipefail

          zip -r -9 "${{ steps.meta.outputs.zipfile }}" ./cyrus
          test -f "${{ steps.meta.outputs.zipfile }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.artifact }}
          path: ${{ steps.meta.outputs.zipfile }}
          if-no-files-found: error

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ steps.meta.outputs.datetime }}
          name: "Cyrus Nightly - ${{ steps.meta.outputs.datetime }}"
          prerelease: true
          generate_release_notes: false
          files: ${{ steps.meta.outputs.zipfile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
