name: Build and Upload Cyrus Lang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Rust (latest version)
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    # Install GCC and libgccjit-12-dev
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libgccjit-12-dev

    # Build the project with Cargo
    - name: Build project with Cargo
      run: cargo build --release

    # Upload the built binary as an artifact
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cyrus
        path: ./target/release/cyrus
