name: Build & Upload Cyrus Lang

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y software-properties-common llvm-18 llvm-18-dev clang zlib1g zlib1g-dev libpolly-18-dev

      - name: Build 
        run: cargo build --verbose --release

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # - name: Run tests
      #   run: cargo test --all --verbose

      - name: Collect files in single directory
        run: |
          mkdir cyrus
          cp ./target/release/cyrus ./cyrus
          cp ./scripts/install.sh ./cyrus
          cp -r ./stdlib ./cyrus

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyrus-linux
          path: ./cyrus
