name: Build and Upload Cyrus Lang

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc

      - name: Download and install GCC fork
        run: |
          curl -LO https://github.com/antoyo/gcc/releases/latest/download/gcc-15.deb
          sudo dpkg --force-overwrite -i gcc-15.deb

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo test --verbose

      - name: Merge binary and mandatory files
        run: |
          mkdir cyrus
          cp ./target/release/cyrus ./cyrus
          cp -r ./stdlib ./cyrus
          tar -cvf ./cyrus.tar ./cyrus

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyrus
          path: ./cyrus.tar
          compression-level: 0
