name: Rust Unit Testing

on:
  push:
    branches: [ "bootstrap-compiler" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run:  |
        sudo apt update
        sudo apt install gcc libgccjit-14-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --workspace
